// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	likescomment "sipencari-api/businesses/likes_comment"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: idMissing, idComment
func (_m *Repository) GetAll(idMissing string, idComment string) []likescomment.Domain {
	ret := _m.Called(idMissing, idComment)

	var r0 []likescomment.Domain
	if rf, ok := ret.Get(0).(func(string, string) []likescomment.Domain); ok {
		r0 = rf(idMissing, idComment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]likescomment.Domain)
		}
	}

	return r0
}

// GetByID provides a mock function with given fields: idLike, idMissing, idComment
func (_m *Repository) GetByID(idLike string, idMissing string, idComment int) likescomment.Domain {
	ret := _m.Called(idLike, idMissing, idComment)

	var r0 likescomment.Domain
	if rf, ok := ret.Get(0).(func(string, string, int) likescomment.Domain); ok {
		r0 = rf(idLike, idMissing, idComment)
	} else {
		r0 = ret.Get(0).(likescomment.Domain)
	}

	return r0
}

// Like provides a mock function with given fields: idUser, idMissing, idComment, likeDomain
func (_m *Repository) Like(idUser string, idMissing string, idComment int, likeDomain *likescomment.Domain) likescomment.Domain {
	ret := _m.Called(idUser, idMissing, idComment, likeDomain)

	var r0 likescomment.Domain
	if rf, ok := ret.Get(0).(func(string, string, int, *likescomment.Domain) likescomment.Domain); ok {
		r0 = rf(idUser, idMissing, idComment, likeDomain)
	} else {
		r0 = ret.Get(0).(likescomment.Domain)
	}

	return r0
}

// Unlike provides a mock function with given fields: idUser, idMissing, idComment
func (_m *Repository) Unlike(idUser string, idMissing string, idComment int) bool {
	ret := _m.Called(idUser, idMissing, idComment)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string, int) bool); ok {
		r0 = rf(idUser, idMissing, idComment)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
